name: CI - Princeton Courses

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run lint
      - run: npm audit --omit=dev